export const mapShowPage = (show, credits, recommendations, certifications, videos) => ({
  name: show.name,
  backdrop: show.backdrop_path,
  poster: show.poster_path,
  rating: certifications.results.filter((v) => v.iso_3166_1 === 'US')[0]?.rating,
  genres: show.genres,
  duration: show.episode_run_time[0],
  country: show.origin_country,
  overview: show.overview,
  seasons: show.seasons,
  creator: show.created_by[0]?.name,
  status: show.status,
  year: show.first_air_date?.substring(0, 4),
  vote_average: show.vote_average,
  vote_count: show.vote_count,
  website: show.homepage,
  network: {
    name: show.networks[0]?.name,
    logo: show.networks[0]?.logo_path,
  },
  cast: credits.cast,
  recommendations: {
    results: recommendations.results,
    total_results: recommendations.total_results,
    total_pages: recommendations.total_pages,
  },
  video: videos[0]?.key,
});
